#!/usr/bin/env bash
rm -rf ~/.vim/bundle
rm -rf ~/.vim/colors
rm -rf ~/.vim/autoload
echo "🙈  Make dirs..."
mkdir ~/.vim
mkdir ~/.vim/swap
mkdir ~/.vim/backup
mkdir ~/.vim/colors
mkdir -p ~/.git_template/hooks
echo "🙉 Clone vim plugins..."
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim
echo "🙊 Put things where they belong..."
mv ./autoload/* ~/.vim/autoload/
mv ./.vimrc ~/.vimrc
mv ./.bash_profile ~/.bash_profile
mv ./.profile ~/.profile
mv ./.bashrc ~/.bashrc
mv ./.gitconfig ~/.gitconfig
mv ./.cvsignore ~/.cvsignore
mv ./.tmux.conf ~/.tmux.conf
mv ./.git_template/hooks/* ~/.git_template/hooks/
echo "🐒 Done! (make sure git hooks are executable and brew install ctags)"
